// ==UserScript==
// @name         SimpCity & SocialMediaGirls — Full Redesign
// @namespace    http://tampermonkey.net/
// @version      3.12.6
// @author       claudiogepeto
// @description  Topbar + dock + filter bar redesign · grid/list thread view w/ placeholders · full images + portrait grid · redgifs embeds · pixeldrain/bunkr link cards · auto-expand spoilers · media feed · post media download · skip link warning · reveal like-gated posts
// @match        https://simpcity.cr/*
// @match        https://simpcity.su/*
// @match        https://forums.socialmediagirls.com/*
// @grant        GM_xmlhttpRequest
// @grant        GM_download
// @grant        GM_setValue
// @grant        GM_getValue
// @connect      api.redgifs.com
// @connect      media.redgifs.com
// @connect      redgifs.com
// @connect      platform.twitter.com
// @connect      api.fxtwitter.com
// @connect      api.vxtwitter.com
// @connect      video.twimg.com
// @connect      pbs.twimg.com
// @connect      instagram.com
// @connect      *
// @run-at       document-start
// @license      MIT
// ==/UserScript==

// GENERATED by scripts/xenforo/build.js — do not edit this script.js directly.
// Edit sources in scripts/xenforo/parts/*.js and run: node scripts/xenforo/build.js
//
// ============================================================================
//  MODERN SIMPCITY / SOCIALMEDIAGIRLS  ·  userscript único (Tampermonkey)
// ============================================================================
//  Navegar: Cmd/Ctrl+F num nome de função (`function rgBuild`) ou num banner de
//  seção. O índice "ONDE ESTÁ CADA COISA" está em ORDEM DE ARQUIVO.
//
// ── COMO FUNCIONA (modelo mental — leia ANTES de mexer) ─────────────────────
//  2 FÓRUNS, 1 SCRIPT. No boot detecta o site e marca <html> com smg-sc (SimpCity)
//  ou smg-smg (SocialMediaGirls). ~96% do código é comum; o que diverge por fórum
//  é gated por essas classes. A CSS inteira é temática via variáveis --smg-*.
//
//  CICLO DE VIDA (o coração de tudo):
//    boot() → processAll() roda TODAS as features 1× e instala um MutationObserver
//    no body. QUALQUER mutação do DOM → scheduleRun() → requestAnimationFrame →
//    processAll() DE NOVO (no máx 1×/frame). Como o próprio processAll muta o DOM,
//    ele roda quase todo frame enquanto a página muda/scrolla.
//    ⇒ REGRA DE OURO: todo pass PRECISA sair BARATO quando não há nada novo.
//      Padrão: seletor com `:not([data-marcador])` + SETAR o marcador ANTES de
//      qualquer return. Esquecer = re-escaneia o documento inteiro todo frame = trava.
//
//  PIPELINE DE VÍDEO (redgifs · players nativos):
//    1) acha o embed: iframe nativo ou loader do fórum (applyRedgifsPlayer).
//    2) resolve o mp4: redgifs = API (rgVideo).
//    3) monta NOSSO <video> + controles próprios (rgBuild/buildNativeVideo → rgControls).
//    4) lazy: rgLoadIO carrega perto da viewport (fila rgTasks, máx 3 juntos, ordenada
//       por distância da tela — makeTaskQueue em 06-helpers);
//       rgPlayIO toca mudo ao ficar ≥40% visível e pausa ao sair.
//    5) carga: streaming DIRETO (no-referrer) → se der erro, BLOB (Referer forjado).
//    6) à prova de falha: qualquer erro → rgRestore() recoloca o iframe nativo.
//
//  MASONRY do post: collectGalleryBlocks() junta imgs+embeds; buildPostGallery()
//    distribui em N colunas por JS (coluna mais curta = Pinterest, sem recarregar o
//    que já está posto). O visualizador cheio (tiktok/zoom/slides) = openMediaFeed().
//
//  GOTCHAS que já queimaram (memória do projeto · [[script-passes-traps]]):
//    • CSS vive num template `…` (backtick) em injectStyles → NUNCA backtick dentro
//      de comentário/conteúdo da CSS. Validar: node --check + contador de chaves {}.
//    • esconder via JS algo com `!important` na CSS → setProperty('…','…','important').
//    • iframe com display:none CONTINUA tocando áudio → REMOVER, não esconder.
//    • marcar o nó ANTES do early-return (ver REGRA DE OURO acima).
//
// ── ONDE ESTÁ CADA COISA (ordem de arquivo) ─────────────────────────────────
//  CONFIG ............ DEFAULT_FEATURES, FEATURES, gmGet/gmSet, saveFeatures, SETTINGS_META
//  i18n .............. IS_PT, I18N_PT, i18n(), i18nDom(), navHref()
//  sessão ............ isLoggedIn(), nativeLoginLink/loginHref/registerHref, wireAuthClick (visitante)
//  ÍCONES ............ ICONS{}, SMG_LOGO_HTML, SMG_PH_MARK/SC_PH_MARK, SMG_FAVICON
//  CSS ............... injectStyles() + parts/styles/*  ← fragmentos por contexto, montados em ordem
//  HELP texto/url .... getBigUrl, cleanText, smgIsWatching, waitForElement
//  HELP UI ........... makeDockButton/makeDockLink, setBtnIcon/Label, makeDivider/Group, readPageJump
//  POST filtro ....... applyAuthorFilter
//  POST teclado ...... setupKeyboardShortcuts
//  POST scroll-inf ... setupInfiniteScroll
//  IMG + MASONRY ..... getThumbIO/getFullIO, processImages, collectGalleryBlocks,
//                      blockRelH, buildPostGallery, buildPostGalleries
//  REDGIFS + PLAYER .. GMX, rgIdFrom, rgToken, rgVideo, rgBlob, getRgLoadIO/getRgPlayIO,
//                      rgTasks(fila), rgPlayIfVisible, rgLoad, rgViaDirect/rgViaBlob, rgRestore,
//                      rgBuild, rgControls, rgStart, buildNativeVideo, rgLoadUrl/rgStartUrl,
//                      rgHidePlaceholder, applyRedgifsPlayer
//  autoload/spoiler .. autoLoadRedgifs, autoExpandSpoilers
//  DOCK (nav post) ... setupPostNavigation()  ← GRANDE: pager, goto, filtro de lista, view-toggle,
//                      download, sheet mobile, e a BUSCA (history/chips/doSearch)
//  busca títulos ..... enableSearchTitlesOnly
//  FEED + LIGHTBOX ... setupImageClickFeed, collectMediaFrom, gal* (galeria paginada),
//                      openMediaFeed()  ← visualizador cheio (slides/zoom/mute)
//  LISTAGEM .......... markThreadGridContainer, badges reativos, styleArticleCards, markGridPlaceholders
//  HOME (forum_list) . mergeSmallHomeSections, relocateSimpcityNodes/relocateSmgNodes, expandSubForums,
//                      splitTransSection, sort/reorderHomeSections, makeHomeCardsClickable,
//                      buildHomeFeed, layoutHomeSidebar
//  THREAD filter bar . smgBarBtn/Pop/Jump/Pager/Sort/Primary/More, buildFilterBars, fetchXfList
//  THUMB cache ....... threadThumbUrl, thumbCacheGet/Put, harvestThreadThumbs (foto da thread nos
//                      alertas, colhida das listagens que já passam pela tela — sem request extra)
//  ALERTAS ........... markAlertRead, paintAlertThumb/repaintAlertThumbs, cleanAlertRow, groupAlerts, cleanAlertList
//  RAIL docked ....... railFetch, watchedRow, buildAlertsDock, railRefresh/More/ShowTab,
//                      open/close/toggleAlertsDock, setupAlertsDock
//                      (painel fixo à direita: abas Alertas + Seguindo)
//  TOPBAR ............ buildTopbar()  ← GRANDE: logo, nav, popovers, sheets mobile
//  HOVER preview ..... dcThumbUrl, setupThumbPreview
//  PAINT runtime ..... classifyPaintPage, skeletons, readiness e handoff estável por página
//  — daqui pra baixo: features definidas tarde no arquivo + o INIT —
//  favicon (SMG) ..... setFavicon
//  REDIRECT unwrap ... b64decode, decodeProxyHref, bindProxyClick, unwrapRedirectLinks, handleRedirectPage
//  REVEAL liked(SMG) . revealLikedPosts, revealPost, markRevealing
//  DOWNLOAD .......... smgDownload, collectPostMedia, downloadAllMedia, dockBadge
//  DIRECT media ...... processDirectMedia  (.mp4/img direto → <video>/<img>)
//  GROUP links ....... linkLabel, groupPostLinks  (file-hosts → chips)
//  INIT .............. safe(), processAll(), scheduleRun(), detectPageClasses(), boot()
// ============================================================================

(function () {
    'use strict';

    // CRITICAL PAINT GATE: this is intentionally the first executable code in the
    // bundle. Tampermonkey can start a document-start userscript after the browser
    // has already parsed enough HTML to paint XenForo once, so the full runtime CSS
    // is too late to be the first line of defence. Keep this preflight tiny and
    // route-based; the normal gate takes ownership as soon as the complete CSS and
    // skeleton are mounted.
    const SMG_CRITICAL_PAINT_STYLE_ID = 'smg-critical-paint';
    const smgCriticalPaintRoot = document.documentElement;
    const smgCriticalPaintPath = location.pathname || '/';
    const smgCriticalPaintRoute = smgCriticalPaintPath === '/'
        || /\/(?:threads|forums|watched|whats-new|tags|categories|search)(?:\/|$)/i.test(smgCriticalPaintPath)
        || /\/account\/bookmarks(?:\/|$)/i.test(smgCriticalPaintPath);
    const smgCriticalPaintDisabled = (() => {
        try {
            if (typeof GM_getValue === 'function' && String(GM_getValue('smg-off', '0')) === '1') return true;
            return localStorage.getItem('smg-off') === '1';
        } catch (e) {
            return false;
        }
    })();

    if (smgCriticalPaintRoot && smgCriticalPaintRoute && !smgCriticalPaintDisabled) {
        smgCriticalPaintRoot.classList.add('smg-critical-paint');
        if (!document.getElementById(SMG_CRITICAL_PAINT_STYLE_ID)) {
            const criticalStyle = document.createElement('style');
            criticalStyle.id = SMG_CRITICAL_PAINT_STYLE_ID;
            criticalStyle.textContent = `
                html.smg-critical-paint,
                html.smg-critical-paint body {
                    background: #101113 !important;
                    overflow: hidden !important;
                }
                html.smg-critical-paint body {
                    visibility: hidden !important;
                    pointer-events: none !important;
                }
                html.smg-critical-paint body > * {
                    visibility: hidden !important;
                }
            `;
            (document.head || smgCriticalPaintRoot).appendChild(criticalStyle);
        }
        // If a later part fails, do not leave a real page permanently invisible.
        setTimeout(releaseCriticalPaintGate, 5000);
    }

    function releaseCriticalPaintGate() {
        if (smgCriticalPaintRoot) smgCriticalPaintRoot.classList.remove('smg-critical-paint');
    }
